title: Deemon Redux
description: Deemon Redux is a monitoring utility for new artist releases with email alerts and automated downloading via deemix
url: "https://mon5termatt.github.io"
baseurl: "/deemon-redux"
repository: mon5termatt/deemon-redux

remote_theme: just-the-docs/just-the-docs@v0.10.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

permalink: pretty

aux_links:
  PyPI:
    - "https://pypi.org/project/deemon-redux/"
  GitHub:
    - "https://github.com/mon5termatt/deemon-redux"

color_scheme: nil
search_enabled: true
heading_anchors: true

footer_content: "Deemon Redux is a continuation of the archived <a href=\"https://github.com/digitalec/deemon\">deemon</a> project."
